version = 0.1
[default.deploy.parameters]
stack_name = "sam-demo-app"
resolve_s3 = true
s3_prefix = "sam-demo-app"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = [
    "Env=default"
]

[dev.deploy.parameters]
stack_name = "sam-demo-app"
resolve_s3 = true
s3_prefix = "sam-demo-app"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = [
    "Env=dev"
]

[qa.deploy.parameters]
stack_name = "sam-demo-app"
resolve_s3 = true
s3_prefix = "sam-demo-app"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = [
    "Env=qa"
]
